<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://myitforum.com/myitforumwp/author/ryan2065/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$strColID = $args[0]
$strColName = $args[1]
$strColMemberCount = $args[2]
$strServer = $args[3]
$strNamespace = $args[4]
$script:ActionCancel = $false
$Popup = new-object -comobject wscript.shell


function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$StartBtn = New-Object System.Windows.Forms.Button
$NewCacheSizeBx = New-Object System.Windows.Forms.TextBox
$CachSizeLbl = New-Object System.Windows.Forms.Label
$ErrorLbl = New-Object System.Windows.Forms.Label
$ErrorBox = New-Object System.Windows.Forms.RichTextBox
$label5 = New-Object System.Windows.Forms.Label
$FinishedLbl = New-Object System.Windows.Forms.Label
$OffLbl = New-Object System.Windows.Forms.Label
$SuccessLbl = New-Object System.Windows.Forms.Label
$ProgressBar = New-Object System.Windows.Forms.ProgressBar
$ColNameLbl = New-Object System.Windows.Forms.Label
$OffBox = New-Object System.Windows.Forms.RichTextBox
$SuccessBox = New-Object System.Windows.Forms.RichTextBox
$CancelBtn = New-Object System.Windows.Forms.Button
$ReRunBtn = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$ReRunBtn_OnClick= 
{
$ArgList = @()
$ArgList += @("`"C:\Program Files\SCCMConsoleExtensions\SilentOpenPS.vbs`"")
$ArgList += @("`"C:\Program Files\SCCMConsoleExtensions\ChangeCacheCol.ps1`"")
$ArgList += @("`"$strColID`"")
$ArgList += @("`"$strColName`"")
$ArgList += @("`"$strColMemberCount`"")
$ArgList += @("`"$strServer`"")
$ArgList += @("`"$strNamespace`"")
Start-Process wscript.exe -ArgumentList $ArgList
$form1.Close()
}

$CancelBtn_OnClick={$script:ActionCancel = $true}

$StartBtn_OnClick= 
{
	$NewCacheSize = $NewCacheSizeBx.Text
	$Refnum = 0
	If ($NewCacheSize.Length -eq 0) {}
	elseif ($NewCacheSize -ne "" -and [System.Int32]::TryParse($NewCacheSize, [ref]$refnum)){
		$CachSizeLbl.Visible = $false
		$NewCacheSizeBx.Visible = $false
		$StartBtn.Visible = $false
		$ProgressBar.Visible = $true
		$count = 0
		$SuccNum = 0
		$OffNum = 0
		$ErrorNum = 0
		$ReRunBtn.Enabled = $false
		$ProgressBar.Maximum = $strColMemberCount
		$SuccessArray = $null
		$OffArray = $null
		$ErrorArray = $null
		$strSuccessBoxText = $null
		$strOffBoxText = $null
		$strErrorBoxText = $null
		$Jobs = "ChangeCache_" + $strColID
		$strQuery = "select Name from SMS_CM_RES_COLL_$strColID"
		Get-WmiObject -Query $strQuery -Namespace $strNamespace -ComputerName $strServer | ForEach-Object {
			if ($script:ActionCancel -eq $true){break;}
			[System.Windows.Forms.Application]::DoEvents()
			$CompName = $_.Name
			Start-Job -Name $Jobs -ArgumentList $CompName,$NewCacheSize -ScriptBlock {
				$CompName = $null
				$CompName = $args[0]
				$NewCacheSize = $args[1]
				$strErrorMsg = "$CompName \/Off\/"
				If (test-connection -computername $CompName -count 1 -quiet){
					$Error.Clear()
					$cachesize = Get-WmiObject -ComputerName $CompName -Class CacheConfig -Namespace root\ccm\softmgmtagent
					$cachesize.Size = "$NewCacheSize"
					$cachesize.Put() | Out-Null
					if($Error[0]){$strErrorMsg = "$CompName \/WMI Error\/"}
					else{$strErrorMsg = "$CompName \/Successful\/"}}
				Write-Output $strErrorMsg
			} | Out-Null
			Receive-Job -Name $Jobs | ForEach-Object {
				$count++
				$strOutput = $_
				$strOutput = $strOutput | Out-String
				if ($strOutput.contains("\/Successful\/")){
					$strSuccessBoxText = $strSuccessBoxText + $strOutput.replace(" \/Successful\/","")
					$SuccessArray += @($strOutput.replace(" \/Successful\/",""))
					$SuccNum++
				}
				elseif ($strOutput.contains("\/Off\/")){
					$strOffBoxText = $strOffBoxText + $strOutput.replace(" \/Off\/","")
					$OffArray += @($strOutput.replace(" \/Off\/",""))
					$OffNum++
				}
				elseif ($strOutput.contains("\/WMI Error\/")){
					$strErrorBoxText = $strErrorBoxText + $strOutput.replace(" \/WMI Error\/","")
					$ErrorArray += @($strOutput.replace(" \/WMI Error\/",""))
					$ErrorNum++
				}
			}
			$ProgressBar.Value = $count
			$SuccessBox.Text = $strSuccessBoxText
			$OffBox.Text = $strOffBoxText
			$ErrorBox.Text = $strErrorBoxText
			$ErrorScrollTo = $ErrorBox.Text.Length - 250
			$SuccessScrollTo = $SuccessBox.Text.Length - 250
			$OffScrollTo = $OffBox.Text.Length - 250
			$SuccessBox.Select($SuccessScrollTo,0)
			$SuccessBox.ScrolltoCaret()
			$OffBox.Select($OffScrollTo,0)
			$OffBox.ScrolltoCaret()
			$ErrorBox.Select($ErrorScrollTo,0)
			$ErrorBox.ScrolltoCaret()
			$SuccessLbl.Text = "$SuccNum Successful"
			$OffLbl.Text = "$OffNum Off"
			$ErrorLbl.Text = "$ErrorNum Errors"
			while (((get-job | where-object { $_.Name -like "$Jobs" -and $_.State -eq "Running" }) | measure).Count -gt 20){
					[System.Windows.Forms.Application]::DoEvents()
					Start-Sleep -Seconds 1
					if ($script:ActionCancel -eq $true){break;}
			}
		}
		while (((get-job | where-object { $_.Name -like "$Jobs" -and $_.State -eq "Running" }) | measure).Count -gt 0){
			Start-Sleep -Seconds 1
			[System.Windows.Forms.Application]::DoEvents()
		}	
		$strSuccessBoxText = $null
		$strOffBoxText = $null
		$strErrorBoxText = $null
		Receive-Job -Name $Jobs | ForEach-Object {
			$strOutput = $_
			$strOutput = $strOutput | Out-String
			if ($strOutput.contains("\/Successful\/")){
				$SuccessArray += @($strOutput.replace(" \/Successful\/",""))
				$SuccNum++
			}
			elseif ($strOutput.contains("\/Off\/")){
				$OffArray += @($strOutput.replace(" \/Off\/",""))
				$OffNum++
			}
			elseif ($strOutput.contains("\/WMI Error\/")){
				$ErrorArray += @($strOutput.replace(" \/WMI Error\/",""))
				$ErrorNum++
			}
		}
		$SuccessArray = $SuccessArray | Sort-Object
		$OffArray = $OffArray | Sort-Object
		$ErrorArray = $ErrorArray | Sort-Object
		foreach ($instance in $ErrorArray){$strErrorBoxText = $strErrorBoxText + $instance}
		foreach ($instance in $SuccessArray) {$strSuccessBoxText = $strSuccessBoxText + $instance}
		foreach ($instance in $OffArray){$strOffBoxText = $strOffBoxText + $instance}
		$SuccessBox.Text = $strSuccessBoxText
		$ErrorBox.Text = $strErrorBoxText
		$OffBox.Text = $strOffBoxText
		$SuccessLbl.Text = "$SuccNum Successful"
		$OffLbl.Text = "$OffNum Off"
		$ErrorLbl.Text = "$ErrorNum Errors"
		$ProgressBar.Visible = $False
		$ReRunBtn.Enabled = $true
		$FinishedLbl.Visible = $True
		$CancelBtn.Enabled = $false
	}
	else{$Popup.popup("Please enter in a number to start",0,"Error",16)}
}

$OnLoadForm_StateCorrection=
{
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 356
$System_Drawing_Size.Width = 464
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.FormBorderStyle = 1
$form1.MaximizeBox = $False
$form1.Name = "form1"
$form1.Text = "Change Cache Size"


$StartBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 358
$System_Drawing_Point.Y = 41
$StartBtn.Location = $System_Drawing_Point
$StartBtn.Name = "StartBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$StartBtn.Size = $System_Drawing_Size
$StartBtn.TabIndex = 14
$StartBtn.Text = "Start"
$StartBtn.UseVisualStyleBackColor = $True
$StartBtn.add_Click($StartBtn_OnClick)

$form1.Controls.Add($StartBtn)

$NewCacheSizeBx.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 245
$System_Drawing_Point.Y = 43
$NewCacheSizeBx.Location = $System_Drawing_Point
$NewCacheSizeBx.Name = "NewCacheSizeBx"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 78
$NewCacheSizeBx.Size = $System_Drawing_Size
$NewCacheSizeBx.TabIndex = 13

$form1.Controls.Add($NewCacheSizeBx)

$CachSizeLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 40
$CachSizeLbl.Location = $System_Drawing_Point
$CachSizeLbl.Name = "CachSizeLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 227
$CachSizeLbl.Size = $System_Drawing_Size
$CachSizeLbl.TabIndex = 12
$CachSizeLbl.Text = "Please enter new cache size in MB:"
$CachSizeLbl.TextAlign = 64

$form1.Controls.Add($CachSizeLbl)

$ErrorLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 310
$System_Drawing_Point.Y = 77
$ErrorLbl.Location = $System_Drawing_Point
$ErrorLbl.Name = "ErrorLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$ErrorLbl.Size = $System_Drawing_Size
$ErrorLbl.TabIndex = 11
$ErrorLbl.Text = "$errornum Errors"

$form1.Controls.Add($ErrorLbl)

$ErrorBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 310
$System_Drawing_Point.Y = 103
$ErrorBox.Location = $System_Drawing_Point
$ErrorBox.Name = "ErrorBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$ErrorBox.Size = $System_Drawing_Size
$ErrorBox.TabIndex = 10
$ErrorBox.Text = ""

$form1.Controls.Add($ErrorBox)

$label5.AutoSize = $True
$label5.DataBindings.DefaultDataSourceUpdateMode = 0
$label5.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 331
$label5.Location = $System_Drawing_Point
$label5.Name = "label5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 13
$System_Drawing_Size.Width = 132
$label5.Size = $System_Drawing_Size
$label5.TabIndex = 9
$label5.Text = "Written by Ryan Ephgrave"

$form1.Controls.Add($label5)

$FinishedLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$FinishedLbl.Location = $System_Drawing_Point
$FinishedLbl.Name = "FinishedLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 440
$FinishedLbl.Size = $System_Drawing_Size
$FinishedLbl.TabIndex = 8
$FinishedLbl.Text = "Finished"
$FinishedLbl.TextAlign = 32
$FinishedLbl.Visible = $False
$FinishedLbl.add_Click($handler_FinishedLbl_Click)

$form1.Controls.Add($FinishedLbl)

$OffLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 165
$System_Drawing_Point.Y = 77
$OffLbl.Location = $System_Drawing_Point
$OffLbl.Name = "OffLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$OffLbl.Size = $System_Drawing_Size
$OffLbl.TabIndex = 7
$OffLbl.Text = "$OffNum Off"

$form1.Controls.Add($OffLbl)

$SuccessLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 77
$SuccessLbl.Location = $System_Drawing_Point
$SuccessLbl.Name = "SuccessLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$SuccessLbl.Size = $System_Drawing_Size
$SuccessLbl.TabIndex = 6
$SuccessLbl.Text = "$SuccNum Successful"

$form1.Controls.Add($SuccessLbl)

$ProgressBar.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$ProgressBar.Location = $System_Drawing_Point
$ProgressBar.Name = "ProgressBar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 437
$ProgressBar.Size = $System_Drawing_Size
$ProgressBar.Step = 1
$ProgressBar.Style = 1
$ProgressBar.TabIndex = 5
$ProgressBar.Visible = $False

$form1.Controls.Add($ProgressBar)

$ColNameLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$ColNameLbl.Location = $System_Drawing_Point
$ColNameLbl.Name = "ColNameLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 437
$ColNameLbl.Size = $System_Drawing_Size
$ColNameLbl.TabIndex = 4
$ColNameLbl.Text = "$strColName"
$ColNameLbl.TextAlign = 32

$form1.Controls.Add($ColNameLbl)

$OffBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 165
$System_Drawing_Point.Y = 103
$OffBox.Location = $System_Drawing_Point
$OffBox.Name = "OffBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$OffBox.Size = $System_Drawing_Size
$OffBox.TabIndex = 3
$OffBox.Text = ""
$OffBox.WordWrap = $False

$form1.Controls.Add($OffBox)

$SuccessBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 103
$SuccessBox.Location = $System_Drawing_Point
$SuccessBox.Name = "SuccessBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$SuccessBox.Size = $System_Drawing_Size
$SuccessBox.TabIndex = 2
$SuccessBox.Text = ""
$SuccessBox.WordWrap = $False

$form1.Controls.Add($SuccessBox)

$CancelBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 374
$System_Drawing_Point.Y = 326
$CancelBtn.Location = $System_Drawing_Point
$CancelBtn.Name = "CancelBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$CancelBtn.Size = $System_Drawing_Size
$CancelBtn.TabIndex = 1
$CancelBtn.Text = "Cancel"
$CancelBtn.UseVisualStyleBackColor = $True
$CancelBtn.add_Click($CancelBtn_OnClick)

$form1.Controls.Add($CancelBtn)

$ReRunBtn.DataBindings.DefaultDataSourceUpdateMode = 0
$ReRunBtn.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 270
$System_Drawing_Point.Y = 326
$ReRunBtn.Location = $System_Drawing_Point
$ReRunBtn.Name = "ReRunBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ReRunBtn.Size = $System_Drawing_Size
$ReRunBtn.TabIndex = 0
$ReRunBtn.Text = "Rerun"
$ReRunBtn.UseVisualStyleBackColor = $True
$ReRunBtn.add_Click($ReRunBtn_OnClick)

$form1.Controls.Add($ReRunBtn)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

GenerateForm