<#
Written by Ryan Ephgrave for ConfigMgr 2012 Right Click Tools
http://myitforum.com/myitforumwp/author/ryan2065/
GUI Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
#>

$strColID = $args[0]
$strColName = $args[1]
$strColMemberCount = $args[2]
$strAction = $args[3]
$strActionName = $args[4]
$strServer = $args[5]
$strNamespace = $args[6]
$script:ActionCancel = $false

function GenerateForm {

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$ActionColForm = New-Object System.Windows.Forms.Form
$ErrorLbl = New-Object System.Windows.Forms.Label
$ErrorBox = New-Object System.Windows.Forms.RichTextBox
$label5 = New-Object System.Windows.Forms.Label
$FinishedLbl = New-Object System.Windows.Forms.Label
$FailLbl = New-Object System.Windows.Forms.Label
$SuccessLbl = New-Object System.Windows.Forms.Label
$ProgressBar = New-Object System.Windows.Forms.ProgressBar
$ColNameLbl = New-Object System.Windows.Forms.Label
$OffBox = New-Object System.Windows.Forms.RichTextBox
$SuccessBox = New-Object System.Windows.Forms.RichTextBox
$CancelBtn = New-Object System.Windows.Forms.Button
$ReRunBtn = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$ReRunBtn_OnClick= 
{
$ArgList = @()
$ArgList += @("`"C:\Program Files\SCCMConsoleExtensions\SilentOpenPS.vbs`"")
$ArgList += @("`"C:\Program Files\SCCMConsoleExtensions\ClientActionsCol.ps1`"")
$ArgList += @("`"$strColID`"")
$ArgList += @("`"$strColName`"")
$ArgList += @("`"$strColMemberCount`"")
$ArgList += @("`"$strAction`"")
$ArgList += @("`"$strActionName`"")
$ArgList += @("`"$strServer`"")
$ArgList += @("`"$strNamespace`"")
Start-Process wscript.exe -ArgumentList $ArgList
$ActionColForm.Close()
}

$CancelBtn_OnClick={$script:ActionCancel = $true}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$ActionColForm.WindowState = $InitialFormWindowState
	$count = 0
	$SuccNum = 0
	$OffNum = 0
	$ErrorNum = 0
	$objpopup = new-object -comobject wscript.shell
	$ReRunBtn.Enabled = $false
	$ProgressBar.Maximum = $strColMemberCount
	$SuccessArray = $null
	$OffArray = $null
	$ErrorArray = $null
	$strSuccessBoxText = $null
	$strOffBoxText = $null
	$strErrorBoxText = $null
	$Jobs = "ClientAction_" + $strColID
	$strQuery = "select Name from SMS_CM_RES_COLL_$strColID"
	Get-WmiObject -Query $strQuery -Namespace $strNamespace -ComputerName $strServer | ForEach-Object {
		if ($script:ActionCancel -eq $true){break;}
		[System.Windows.Forms.Application]::DoEvents()
		$CompName = $_.Name
		Start-Job -Name $Jobs -ArgumentList $CompName,$strAction -ScriptBlock {
			$CompName = $null
			$CompName = $args[0]
			$strAction = $args[1]
			$strErrorMsg = "$CompName \/Off\/"
			If (test-connection -computername $CompName -count 1 -quiet){
				$Error.Clear()
				$WMIPath = "\\" + $CompName + "\root\ccm:SMS_Client"
				$SMSwmi = [wmiclass] $WMIPath
				[Void]$SMSwmi.TriggerSchedule($strAction)
				if($Error[0]){$strErrorMsg = "$CompName \/WMI Error\/"}
				else{$strErrorMsg = "$CompName \/Successful\/"}}
			Write-Output $strErrorMsg
		} | Out-Null
		Receive-Job -Name $Jobs | ForEach-Object {
			$count++
			$strOutput = $_
			$strOutput = $strOutput | Out-String
			if ($strOutput.contains("\/Successful\/")){
				$strSuccessBoxText = $strSuccessBoxText + $strOutput.replace(" \/Successful\/","")
				$SuccessArray += @($strOutput.replace(" \/Successful\/",""))
				$SuccNum++
			}
			elseif ($strOutput.contains("\/Off\/")){
				$strOffBoxText = $strOffBoxText + $strOutput.replace(" \/Off\/","")
				$OffArray += @($strOutput.replace(" \/Off\/",""))
				$OffNum++
			}
			elseif ($strOutput.contains("\/WMI Error\/")){
				$strErrorBoxText = $strErrorBoxText + $strOutput.replace(" \/WMI Error\/","")
				$ErrorArray += @($strOutput.replace(" \/WMI Error\/",""))
				$ErrorNum++
			}
		}
		$ProgressBar.Value = $count
		$SuccessBox.Text = $strSuccessBoxText
		$OffBox.Text = $strOffBoxText
		$ErrorBox.Text = $strErrorBoxText
		$ErrorScrollTo = $ErrorBox.Text.Length - 250
		$SuccessScrollTo = $SuccessBox.Text.Length - 250
		$OffScrollTo = $OffBox.Text.Length - 250
		$SuccessBox.Select($SuccessScrollTo,0)
		$SuccessBox.ScrolltoCaret()
		$OffBox.Select($OffScrollTo,0)
		$OffBox.ScrolltoCaret()
		$ErrorBox.Select($ErrorScrollTo,0)
		$ErrorBox.ScrolltoCaret()
		$SuccessLbl.Text = "$SuccNum Successful"
		$FailLbl.Text = "$OffNum Off"
		$ErrorLbl.Text = "$ErrorNum Errors"
		while (((get-job | where-object { $_.Name -like "$Jobs" -and $_.State -eq "Running" }) | measure).Count -gt 20){
				[System.Windows.Forms.Application]::DoEvents()
				Start-Sleep -Seconds 1
				if ($script:ActionCancel -eq $true){break;}
		}
	}
	while (((get-job | where-object { $_.Name -like "$Jobs" -and $_.State -eq "Running" }) | measure).Count -gt 0){
		Start-Sleep -Seconds 1
		[System.Windows.Forms.Application]::DoEvents()
	}
	$strSuccessBoxText = $null
	$strOffBoxText = $null
	$strErrorBoxText = $null
	Receive-Job -Name $Jobs | ForEach-Object {
		$strOutput = $_
		$strOutput = $strOutput | Out-String
		if ($strOutput.contains("\/Successful\/")){
			$SuccessArray += @($strOutput.replace(" \/Successful\/",""))
			$SuccNum++
		}
		elseif ($strOutput.contains("\/Off\/")){
			$OffArray += @($strOutput.replace(" \/Off\/",""))
			$OffNum++
		}
		elseif ($strOutput.contains("\/WMI Error\/")){
			$ErrorArray += @($strOutput.replace(" \/WMI Error\/",""))
			$ErrorNum++
		}
	}
	$SuccessArray = $SuccessArray | Sort-Object
	$OffArray = $OffArray | Sort-Object
	$ErrorArray = $ErrorArray | Sort-Object
	foreach ($instance in $ErrorArray){$strErrorBoxText = $strErrorBoxText + $instance}
	foreach ($instance in $SuccessArray) {$strSuccessBoxText = $strSuccessBoxText + $instance}
	foreach ($instance in $OffArray){$strOffBoxText = $strOffBoxText + $instance}
	$SuccessBox.Text = $strSuccessBoxText
	$ErrorBox.Text = $strErrorBoxText
	$OffBox.Text = $strOffBoxText
	$SuccessLbl.Text = "$SuccNum Successful"
	$FailLbl.Text = "$OffNum Off"
	$ErrorLbl.Text = "$ErrorNum Errors"
	$ProgressBar.Visible = $False
	$ReRunBtn.Enabled = $true
	$FinishedLbl.Visible = $True
	$CancelBtn.Enabled = $false
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 356
$System_Drawing_Size.Width = 464
$ActionColForm.ClientSize = $System_Drawing_Size
$ActionColForm.DataBindings.DefaultDataSourceUpdateMode = 0
$ActionColForm.FormBorderStyle = 1
$ActionColForm.MaximizeBox = $False
$ActionColForm.Name = "ActionColForm"
$ActionColForm.Text = "Client Action - $strActionName"

$ErrorLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 310
$System_Drawing_Point.Y = 77
$ErrorLbl.Location = $System_Drawing_Point
$ErrorLbl.Name = "ErrorLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$ErrorLbl.Size = $System_Drawing_Size
$ErrorLbl.TabIndex = 11
$ErrorLbl.Text = "$errornum Errors"

$ActionColForm.Controls.Add($ErrorLbl)

$ErrorBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 310
$System_Drawing_Point.Y = 103
$ErrorBox.Location = $System_Drawing_Point
$ErrorBox.Name = "ErrorBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$ErrorBox.Size = $System_Drawing_Size
$ErrorBox.TabIndex = 10
$ErrorBox.Text = ""

$ActionColForm.Controls.Add($ErrorBox)

$label5.AutoSize = $True
$label5.DataBindings.DefaultDataSourceUpdateMode = 0
$label5.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 331
$label5.Location = $System_Drawing_Point
$label5.Name = "label5"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 13
$System_Drawing_Size.Width = 132
$label5.Size = $System_Drawing_Size
$label5.TabIndex = 9
$label5.Text = "Written by Ryan Ephgrave"

$ActionColForm.Controls.Add($label5)

$FinishedLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$FinishedLbl.Location = $System_Drawing_Point
$FinishedLbl.Name = "FinishedLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 440
$FinishedLbl.Size = $System_Drawing_Size
$FinishedLbl.TabIndex = 8
$FinishedLbl.Text = "Finished"
$FinishedLbl.TextAlign = 32
$FinishedLbl.Visible = $False

$ActionColForm.Controls.Add($FinishedLbl)

$FailLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 165
$System_Drawing_Point.Y = 77
$FailLbl.Location = $System_Drawing_Point
$FailLbl.Name = "FailLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$FailLbl.Size = $System_Drawing_Size
$FailLbl.TabIndex = 7
$FailLbl.Text = "$OffNum Off"

$ActionColForm.Controls.Add($FailLbl)

$SuccessLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 77
$SuccessLbl.Location = $System_Drawing_Point
$SuccessLbl.Name = "SuccessLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 139
$SuccessLbl.Size = $System_Drawing_Size
$SuccessLbl.TabIndex = 6
$SuccessLbl.Text = "$SuccNum Successful"

$ActionColForm.Controls.Add($SuccessLbl)

$ProgressBar.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$ProgressBar.Location = $System_Drawing_Point
$ProgressBar.Name = "ProgressBar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 437
$ProgressBar.Size = $System_Drawing_Size
$ProgressBar.Step = 1
$ProgressBar.Style = 1
$ProgressBar.TabIndex = 5
$ProgressBar.Value = 0

$ActionColForm.Controls.Add($ProgressBar)

$ColNameLbl.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$ColNameLbl.Location = $System_Drawing_Point
$ColNameLbl.Name = "ColNameLbl"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 437
$ColNameLbl.Size = $System_Drawing_Size
$ColNameLbl.TabIndex = 4
$ColNameLbl.Text = "$strColName"
$ColNameLbl.TextAlign = 32

$ActionColForm.Controls.Add($ColNameLbl)

$OffBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 165
$System_Drawing_Point.Y = 103
$OffBox.Location = $System_Drawing_Point
$OffBox.Name = "OffBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$OffBox.Size = $System_Drawing_Size
$OffBox.TabIndex = 3
$OffBox.Text = ""
$OffBox.WordWrap = $False

$ActionColForm.Controls.Add($OffBox)

$SuccessBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 103
$SuccessBox.Location = $System_Drawing_Point
$SuccessBox.Name = "SuccessBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 217
$System_Drawing_Size.Width = 139
$SuccessBox.Size = $System_Drawing_Size
$SuccessBox.TabIndex = 2
$SuccessBox.Text = ""
$SuccessBox.WordWrap = $False

$ActionColForm.Controls.Add($SuccessBox)


$CancelBtn.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 374
$System_Drawing_Point.Y = 326
$CancelBtn.Location = $System_Drawing_Point
$CancelBtn.Name = "CancelBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$CancelBtn.Size = $System_Drawing_Size
$CancelBtn.TabIndex = 1
$CancelBtn.Text = "Cancel"
$CancelBtn.UseVisualStyleBackColor = $True
$CancelBtn.add_Click($CancelBtn_OnClick)

$ActionColForm.Controls.Add($CancelBtn)


$ReRunBtn.DataBindings.DefaultDataSourceUpdateMode = 0
$ReRunBtn.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 270
$System_Drawing_Point.Y = 326
$ReRunBtn.Location = $System_Drawing_Point
$ReRunBtn.Name = "ReRunBtn"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ReRunBtn.Size = $System_Drawing_Size
$ReRunBtn.TabIndex = 0
$ReRunBtn.Text = "Rerun"
$ReRunBtn.UseVisualStyleBackColor = $True
$ReRunBtn.add_Click($ReRunBtn_OnClick)

$ActionColForm.Controls.Add($ReRunBtn)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $ActionColForm.WindowState
#Init the OnLoad event to correct the initial state of the form
$ActionColForm.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$ActionColForm.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
