$COLLECTIONS = "3DS Max 2016",
"Accelio Present View Manager 5.6",
"ActiveState ActivePerl 5.16",
"Admin",
"Adobe Acrobat Professional 10.0",
"Adobe Acrobat Professional 11.0",
"Adobe Acrobat Professional 7.0",
"Adobe Acrobat Professional 9.0",
"Adobe Acrobat Standard 10.0",
"Adobe Acrobat Standard 11.0",
"Adobe Acrobat Standard 7.0",
"Adobe Acrobat Standard 8.0",
"Adobe Acrobat Standard 9.0",
"Adobe Acrobat Standard DC 2015",
"Adobe Application  Manager CS5.5",
"Adobe Creative Cloud",
"Adobe Creative Suite Design Premium CS3",
"Adobe Creative Suite Design Premium CS4",
"Adobe Creative Suite Design Premium CS5",
"Adobe Creative Suite Design Standard CS3",
"Adobe Creative Suite Design Standard CS4",
"Adobe Creative Suite Design Standard CS5",
"Adobe Creative Suite Design Standard CS5.5",
"Adobe Creative Suite Design Standard CS6",
"Adobe Dreamweaver CS3",
"Adobe Dreamweaver CS5",
"Adobe Flash Player",
"Adobe Flash Player 11",
"Adobe Flash Player 14.0",
"Adobe Flash Professional CS4",
"Adobe Framemaker 11.0",
"Adobe FrameMaker 9.0",
"Adobe Illustrator CS3",
"Adobe Illustrator CS4",
"Adobe Illustrator CS5",
"Adobe Illustrator CS6",
"Adobe InDesign CS3",
"Adobe InDesign CS4",
"Adobe InDesign CS6",
"Adobe Photoshop CS3",
"Adobe Photoshop CS4",
"Adobe Photoshop CS5",
"Adobe Photoshop CS6",
"Adobe Photoshop Elements 8.0",
"Adobe Premiere Pro CS3",
"Adobe Premiere Pro CS4",
"Adobe Shockwave Player 10.1",
"Adobe Version Cue CS2",
"Advance CSV Converter 3.0",
"Advance CSV Converter 4.9",
"Advance CSV Converter 5.15",
"ALM_Client",
"Alterna TIFF 1.8",
"Autocad 2016",
"Autodesk 3DS Max 2014",
"Autodesk 3DS Max 2015",
"Autodesk 3ds Max 2016",
"Autodesk 3DS MAX DESIGN 2014",
"Autodesk Fusion 360",
"Autodesk Revit LT 2015",
"Avanstar Quick View Plus 8.0",
"Avaya Message Manager 5.0",
"Borland RunTime",
"BoxSync 4.0",
"Business Objects Advance Analysis",
"Business Objects Dashboard",
"Business Objects Designer 4.1.9",
"Business Objects Driller 4.1.9",
"Business Objects LiveOffice",
"Business Objects Reporter 4.1.9",
"Business Objects SAP Client Tools",
"Business Objects SAP Crystal Report for Enterprise",
"Business Objects SAP Crystal Report Viewer",
"Business Objects SAP Crystal Reports 2011",
"Business Objects Supervisor 4.1.9",
"BusinessUnitSettings",
"CA Workload Desktop Client 11.3",
"Cisco Agent Desktop",
"Cisco Jabber 10.6",
"Cisco Supervisor Desktop",
"Cisco ViewMail 4.0.5",
"ContractLogix-Client_15",
"ContractLogix_Client_10",
"ContractLogix_Client_12",
"Creoview",
"Creoview30",
"CutePDF Writer",
"DameWare Mini Remote Control 7.0",
"DameWare Mini Remote Control 8.0",
"DameWare Remote Control 12.0",
"Dell Bios Update",
"Dell PowerDVD 7.0",
"DisplayLink",
"DLOAgent",
"DWG TrueView 2016",
"DWG Viewer 2010",
"eDrawings 2016",
"EMEA_Systems",
"Encrypt 2000 1.0",
"Encrypted RunAs",
"ESP Workstation 4.2.2",
"ExcelDiff 4.2",
"FastStone Capture 7.7",
"FileMaker Pro 10",
"FileMaker Pro 11",
"FileMaker Pro 13",
"FileNet AP 4.0",
"FileNet IDM 4.0",
"FileNet OrderFullFill 4.0",
"FlexSim 7.0",
"Forte City Fleet Dispatcher",
"Forte City Fleet Requester",
"Forte Core",
"GFI FaxMaker Client 14.1",
"Google Chrome",
"Google Drive",
"GoToMeeting 5.7",
"HelpSpot",
"IBM Client Access 5.3",
"IBM Lotus Notes 5.0.5",
"IETab",
"IndexMatic Pro 2.0",
"Intel-Wireless-Update",
"IPSwitch WsFTP Pro 9.0",
"Ipswitch WS_FTP Professional 2007",
"Java",
"Jing 2",
"JiveLinks",
"LookSoftware NewLook 8.0",
"Macro Systems Cascade Chart Creator 4.05",
"Mandiant Intelligent Response Agent 2.3",
"Mapics XA Client",
"MBI Client 3.5",
"Microsoft .Net Framework 3.5",
"Microsoft .Net Framework 4.0",
"Microsoft .Net Framework 4.5",
"Microsoft Access 2007",
"Microsoft Access 2010",
"Microsoft Access 97",
"Microsoft CRM 4.0",
"Microsoft FrontPage 2003",
"Microsoft Internet Explorer 10.0",
"Microsoft Internet Explorer 11.0",
"Microsoft Internet Explorer 8.0",
"Microsoft Internet Explorer 9.0",
"Microsoft MapPoint  NA 2013",
"Microsoft MapPoint NA 2006",
"Microsoft MapPoint NA 2011",
"Microsoft Office Communicator 2007 R2",
"Microsoft Office Live Meeting 2007",
"Microsoft Office Professional Plus 2007",
"Microsoft Office Professional Plus 2010-x86",
"Microsoft Office SharePoint Designer 2007",
"Microsoft OneNote 2003",
"Microsoft OneNote 2007",
"Microsoft OneNote 2010",
"Microsoft OneNote 2013",
"Microsoft PowerPoint Viewer 2010",
"Microsoft Project Professional 2013",
"Microsoft Project Professional 2016",
"Microsoft Project Standard 2010",
"Microsoft Project Standard 2013",
"Microsoft Project Standard 2016",
"Microsoft SaveAsPDF",
"Microsoft SCOM Agent 2007",
"Microsoft SCOM Console 2007-x64",
"Microsoft SCOM Console 2007-x86",
"Microsoft Sharepoint Workspace 2010",
"Microsoft Streets and Trips 2005",
"Microsoft Streets and Trips 2006",
"Microsoft Streets and Trips 2007",
"Microsoft Streets and Trips 2010",
"Microsoft Streets and Trips 2011",
"Microsoft Visio Professional 2003",
"Microsoft Visio Professional 2007",
"Microsoft Visio Professional 2010",
"Microsoft Visio Professional 2013",
"Microsoft Visio Professional 2016",
"Microsoft Visio Standard 2010",
"Microsoft Visio Standard 2013",
"Microsoft Visio Standard 2016",
"Microsoft Visio Viewer 2016",
"Microsoft Visual Source Safe 2005",
"Microsoft Visual Studio Professional 2003",
"Microsoft Visual Studio Professional 2005",
"Microsoft Visual Studio Professional 2008",
"Microsoft Visual Studio Professional 2010",
"Microsoft Visual Studio Professional 2012",
"Microsoft Visual Studio Professional 2013",
"Microsoft Visual Studio Professional 2015",
"Microsoft Visual Studio Tools 2005",
"Microsoft VPN Client",
"Microsoft VPN Client2",
"Microsoft Windows XP SP3",
"Microsoft Word 2013",
"Mindjet MindManager 14.0",
"MindJet MindManager 15.0",
"Mindjet Mindmanager 16",
"MindJet MindManager 2017",
"Mindjet MindManager 8.0",
"Minitab 16.0",
"Minitab 17.0",
"Minitab Release 15",
"Mozilla Firefox",
"MS Visual Studio Foundation Server 2012",
"mvs2005tools",
"Nitro PDF Professional",
"Nitro Pro 10",
"Nitro Pro 11",
"NotePad ++",
"O365",
"O365Tools",
"O365Updates",
"Open Source 7Zip",
"Open Source Gimp",
"Oracle Client 10.2",
"Oracle Client 11.0",
"Oracle Client 11.2",
"Oracle Client 12.10.10",
"Oracle Client 8.1.6",
"OutStart SoftSim 7.0",
"Pcon",
"PDF to DWG Converter 2013",
"PDFCreator 1.3.2",
"PostScript Viewer 1.1",
"PrimeSys SecureEntry 2.5",
"Print Manager Plus Client Software",
"PROD-740-BWPL6",
"ProTOOLKIT Applications",
"PTC WorkGroup Manager",
"qdPM 8.3",
"Quality Center 11.0",
"Quality Center 12.0",
"Quintus HelpQ 5.1",
"Quintus Line1 5.1",
"Rampant Logic Postscript Viewer 1.1",
"Report Viewer Classic 5.0",
"Revit LT 2014",
"Revit LT 2015",
"RFScanner-Barcode",
"RhinoCAM 2014",
"RiskAnalyst 6.2",
"Roxio DigitalMedia Plus 10.0",
"Roxio DigitalMedia Plus 7.2",
"Roxio DigitalMedia Plus 9.0",
"SafeEnd",
"SAP EPM add-in",
"SAP GUI PROD-720",
"SAP GUI PROD-730",
"SAP GUI PROD-740",
"SAP MDM Console",
"SAP MDM Data Manager",
"SAP MDM Import Manager",
"SAS JMP 11.0",
"SAS JMP 12.0",
"SAS JMP 13.0",
"SCCM 2012 SP1",
"Sigstr",
"Sketchup Pro 2016",
"Sketchup Pro 2017",
"SolarWinds Orion SDK 1.6",
"SolidWorks eDrawings 2015",
"SQL Server Tools 2008R2",
"SSRS 2008",
"SSRS Software",
"Steelcase Desktop Resources",
"Steelcase Desktop Resources 2.0",
"Steelcase Desktop Resources 2.0.old1",
"Steelcase Desktop Resources 2.1",
"Steelcase Email Signature Templates",
"Steelcase Email Signature Templates - Steelcase Brand",
"Steelcase Email Signature Templates - Steelcase Inc",
"Steelcase EMU",
"Steelcase Emu Update Tool",
"Steelcase Sims 2000",
"Steelcase Speed 2000",
"Steelcase Templates US",
"Steelcase Touch Screen Browser Setup",
"Steelcase Virtual Puck",
"SteelRay Project Viewer",
"Symantec Winfax Pro 10.0",
"SynchroFile 1.0",
"TeamViewer",
"TechSmith Camtasia Studio 6.0",
"TechSmith Camtasia Studio 8.0",
"TechSmith Camtasia Studio 8.5",
"TechSmith Deployment Tool",
"Techsmith Snagit 10.0",
"TechSmith Snagit 11.0",
"TechSmith Snagit 12.0",
"Time and Attendance",
"Time Dynamix Crystal Reports Fix",
"TMEE Suite",
"Trend encryption",
"Trend Micro v11",
"TrendMicro OfficeScan Client 10.0-x64",
"TrendMicro OfficeScan Client 10.0-x86",
"V-Ray Workstation 3.0 for 3ds Max",
"VeryPDF Advanced Page Cut 2.0",
"VideoLAN VLC",
"Virtual Puck",
"Vista BitLocker 6.0.6",
"VMWare Tools 5.0",
"Voltage Client",
"Webex",
"Win10",
"Windows Media Sound Files 1.0",
"WinPACES 2000",
"WinZip Computing WinZip 17.0",
"WinZip Computing WinZip 18.0",
"WorkManager",
"WPM Database",
"WRQ ReflectionX 13.0",
"WRQ ReflectionX 14.0",
"Wunderlist"

Foreach ($COLL in $COLLECTIONS) {
New-CMCollection -CollectionType Device -Name $COLL -LimitingCollectionName "All Systems"
}
 